/**
 * yt-studio.schema.json → src/core/options.gen.ts
 *
 * gen_schema.py reflects the installed yt-dlp and drops yt-studio.schema.json,
 * and this file turns that into **types**. So the options in autocomplete =
 * the options of the yt-dlp this repo was built with. They don't come from a
 * model's memory.
 *
 * The checker can pick up a local schema at runtime (src/index.ts), but it
 * can't change the types — the file produced here ships as the .d.ts as is.
 *
 * Half of what the checker did at runtime moves up to compile time here —
 * nonexistent flags become nonexistent methods, and choices become unions.
 *
 * It emits types only. The runtime methods are grown by build.ts from the same
 * schema. Both come from one place (yt-studio.schema.json), so they can't drift.
 *
 *   bun gen_options.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

// Naming rules, JSDoc escaping, and method signatures exist in exactly one copy.
// `yt-studio types` uses the same ones — both generators must emit the same shape.
import { HAND_WRITTEN, doc, optionMethod, selMethod, union } from './src/core/env-types.js';
import { FKEYS, SELECTORS, SEL_HELP } from './src/core/format-grammar.js';
import { CONVERSIONS, FIELDS, FIELD_HELP, OUT_TYPES } from './src/core/output-template.js';
import type { RawSchema } from './src/core/schema.js';

const SCHEMA: RawSchema = JSON.parse(
  readFileSync(new URL('./yt-studio.schema.json', import.meta.url), 'utf8'),
);


// The vocabulary tables are the hand-written layer (format-grammar.ts, output-template.ts).
// Every description shown in autocomplete comes from there.
/** Per-slot vocabulary carried by the schema. Dies on the spot if missing — silently
 * becoming an empty union would turn `Browser` into `never` and every valid call into a type error. */
const vocabOf = (id: string, slot: string): string[] => {
  const v = SCHEMA.options.find(o => o.id === id)?.vocabs?.[slot];
  if (!v?.length) throw new Error(`스키마에 ${id} 의 ${slot} 어휘가 없다`);
  return v;
};

const SELS = SELECTORS.flatMap(([, items]) => items.map(([k]) => k));
const OUT_FIELDS = FIELDS.flatMap(([, items]) => items.map(([k]) => k));
const TYPES = OUT_TYPES.map(([v]) => v).filter(Boolean);

// Keys of NumCond and StrCond. Same order as the operator table (build.ts).
const NUM_CONDS: [key: string, doc: string][] = [
  ['lt', '`<` — less than'], ['lte', '`<=` — at most'], ['gt', '`>` — greater than'],
  ['gte', '`>=` — at least'], ['eq', '`=` — equal'], ['ne', '`!=` — not equal'],
];
const STR_CONDS: [key: string, doc: string][] = [
  ['eq', '`=` — equal'], ['ne', '`!=` — not equal'],
  ['startsWith', '`^=` — starts with'], ['endsWith', '`$=` — ends with'],
  ['includes', '`*=` — contains'], ['matches', '`~=` — matches the regex'],
  ['notStartsWith', '`!^=` — does not start with'], ['notEndsWith', '`!$=` — does not end with'],
  ['notIncludes', '`!*=` — does not contain'], ['notMatches', '`!~=` — does not match the regex'],
];

const fkeyDoc = (k: string): string => doc(FKEYS.find(([n]) => n === k)?.[1]);
const filterProps = FKEYS.map(([k, , t]) =>
  `  /** ${fkeyDoc(k)} */\n  ${k}?: ${t === 'num' ? 'number | NumCond' : 'string | StrCond'} | boolean;`,
).join('\n');

// --match-filters compares -o fields with -f operators. We don't know whether a
// field is numeric, so both are accepted — yt-dlp also decides by looking at the value.
const matchProps = OUT_FIELDS.map(f =>
  `  /** \`${f}\` — ${doc(FIELD_HELP[f])} */\n  ${f}?: number | NumCond | string | StrCond | boolean;`,
).join('\n');

// Don't pass it to map directly — the index would land in optionMethod's second argument.
const optionMethods = SCHEMA.options
  .filter(o => !HAND_WRITTEN.has(o.id))
  .map(o => optionMethod(o)).join('\n\n');

const out = `// Generated by gen_options.ts from yt-studio.schema.json. Do not edit by hand.
//
//   yt-dlp ${SCHEMA.ytdlp_version} · ${SCHEMA.options.length} options
//   bun gen_options.ts

/** The yt-dlp version these types came from. */
export type Version = '${SCHEMA.ytdlp_version}';

/**
 * The same thing, **as a value** too.
 *
 * Types alone can't answer "which version did autocomplete come from?" at
 * runtime. That answer used to come from reading the schema file shipped with
 * the package, which meant places without a file system (browsers) couldn't
 * even ask. Being generated, it can't drift from the type above.
 */
export const TYPES_VERSION: Version = '${SCHEMA.ytdlp_version}';

/** What can be passed to an option that takes a value. */
export type Arg = string | number;

/**
 * A byte count. May carry a unit like \`50K\` or \`44.6M\`, or be a plain number.
 *
 * Ported directly from yt-dlp's \`parse_bytes\`, so \`50KB\` is **not
 * accepted** — that unit isn't in the table. Case-insensitive.
 */
export type Size = number | \`\${number}\${'K' | 'M' | 'G' | 'T' | 'P' | 'E' | 'Z' | 'Y'
  | 'k' | 'm' | 'g' | 't' | 'p' | 'e' | 'z' | 'y'}\`;

/** Number of retries. A number or \`infinite\`. */
export type Retries = number | 'infinite';

/** Browsers \`--cookies-from-browser\` can read cookies from. */
export type Browser = ${union(vocabOf('cookies-from-browser', 'browser'))};

/** Keyring used to decrypt Chromium-family cookies on Linux. */
export type Keyring = ${union(vocabOf('cookies-from-browser', 'keyring'))};

/** Selectors \`-f\` accepts. In the builder they become methods like \`f.bv()\`. */
export type Selector = ${union(SELS)};

/** Method names of the selector factory. \`*\` becomes \`Star\`. */
export type SelMethod = ${union(SELS.map(selMethod))};

/**
 * The selector factory.
 *
 * Takes the expression type as a parameter — importing build.ts's \`Expr\` here
 * would be circular, and a mapped type (\`{ [K in SelMethod]: … }\`) would lose
 * the per-selector descriptions. This file exists so those descriptions show up
 * in the editor, so each one is spelled out on its own line.
 */
export interface FormatFactory<E> {
${SELS.map(s => `  /** \`${s}\` — ${doc(SEL_HELP[s])} */\n  ${selMethod(s)}(filters?: Filters): E;`).join('\n')}
  /** When you need to step outside the grammar. Goes out as is, unchecked. */
  raw(selector: string): E;
}

/** Numeric field comparison. \`loose\` also lets through formats missing the value (\`height<=?1080\`). */
export interface NumCond {
${NUM_CONDS.map(([k, d]) => `  /** ${d} */\n  ${k}?: number;`).join('\n')}
  /** Also lets through formats missing the field — adds \`?\`. */
  loose?: boolean;
}

/** String field comparison. Given several, all of them apply. */
export interface StrCond {
${STR_CONDS.map(([k, d]) => `  /** ${d} */\n  ${k}?: string;`).join('\n')}
  /** Also lets through formats missing the field — adds \`?\`. */
  loose?: boolean;
}

/**
 * Format filters.
 *
 * A plain value is an \`=\` comparison; \`true\`/\`false\` mean present/absent.
 *
 *     { height: { lte: 1080 }, ext: 'mp4', format_note: false }
 *     → [height<=1080][ext=mp4][!format_note]
 */
export interface Filters {
${filterProps}
}

/**
 * Fields \`--match-filters\` looks at. **Operators are the same as \`-f\` filters
 * and fields the same as the \`-o\` template** — that is how yt-dlp defines it
 * ("Any OUTPUT TEMPLATE field").
 *
 * **It must not be closed.** yt-dlp accepts any info dict key (it varies by
 * extractor), so blocking fields not listed here would turn valid conditions
 * into type errors. So known ones show up in autocomplete and the rest stay
 * open — at the cost of not catching typos in field names.
 */
export interface MatchFields {
${matchProps}
  [field: string]: number | NumCond | string | StrCond | boolean | undefined;
}

/** Fields commonly used in the \`-o\` template. For others, \`t.field('name')\`. */
export type OutField = ${union(OUT_FIELDS)};
/** File type prefixed to \`-o\` and \`-P\`. Without one, it applies to every downloaded file. */
export type OutType = ${union(TYPES)};
/** Conversion character at the end of an \`-o\` field. The \`S\` in \`%(title)S\`. */
export type Conversion = ${union(CONVERSIONS.map(([c]) => c))};

/**
 * Field accessors attached to the template tag.
 *
 * Names are yt-dlp's own. camelCase would look nicer but produce names you
 * can't find in the yt-dlp docs.
 */
export interface OutFields<P> {
${OUT_FIELDS.map(f => `  /** \`%(${f})s\` — ${doc(FIELD_HELP[f])} */\n  readonly ${f}: P;`).join('\n')}
}

/** Paths that can be given to \`-P\`. Only \`home\` goes out without a prefix. */
export interface PathMap {
  /** Where downloaded files finally land. */
  home?: string;
  /** Temporary location used while downloading. */
  temp?: string;
${OUT_TYPES.filter(([t]) => t).map(([t, label]) => `  /** ${doc(label)} */\n  ${t}?: string;`).join('\n')}
}

/**
 * Every option of the installed yt-dlp.
 *
 * Declaration-merged with the \`Ytdlp\` class — build.ts grows the runtime
 * methods from the same yt-studio.schema.json, so they always match this interface.
 */
export interface Options {
${optionMethods}
}
`;

writeFileSync(new URL('./src/core/options.gen.ts', import.meta.url), out);
console.log(`options.gen.ts — 옵션 ${SCHEMA.options.length}개 · yt-dlp ${SCHEMA.ytdlp_version}`);
